global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-app"
    static_configs:
      - targets: ["node-app:4040"]

  - job_name: "minio"
    scheme: http
    static_configs:
      - targets: ["minio:9000"]
    metrics_path: "/minio/v2/metrics/cluster"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
